language: node_js
matrix:
    fast_finish: true
node_js:
    - 6.0
notifications:
    email: false
before_install:
    - npm install --global flow-bin@0.52.0
    - npm install
install:
    - npm run test:full
